### ISSUE TITLE
Person name extraction 

### ISSUE THREAD

**Issue by Aj-232425** [pmbaumgartner/binder-notebooks#15]
Hi ,
It was nice repo to go through. But as of now i have something different requirement. What i need is to extract patient name from medical reports. Text format that i have be like : "List of encounters for: Warner, David (DOB ddmmyy) has been given Tdap/pcm . Done precautionary test to the patient: Warner, David." This is the sample text. I want to extract patient name Warner, David both the times(regardless how many times repeat ) from the page. It have previous tokens as you can see "patient" or "list of encounters" etc. How can I do this patient name extraction using MedSpacy. Any help would be appreciated.
Thanks & regards

**Comment by pmbaumgartner** [comment]
I would ask on the MedSpacy discussion forum. https://github.com/medspacy/medspacy/discussions
